project = "hugoreleaser"

[go_settings]
    go_proxy = "https://proxy.golang.org"
    go_exe   = "go"

[build_settings]
    binary  = "hugoreleaser"
    flags   = ["-buildmode", "exe"]
    env     = ["CGO_ENABLED=0"]
    ldflags = ""

[archive_settings]
    name_template = "{{ .Project }}_{{ .Tag | trimPrefix `v` }}_{{ .Goos }}-{{ .Goarch }}"
    extra_files   = [{ source_path = "README.md", target_path = "README.md" }, { source_path = "LICENSE", target_path = "LICENSE" }]
    [archive_settings.type]
        format    = "tar.gz"
        extension = ".tar.gz"

[release_settings]
    name                           = "${HR_RELEASE_NAME}"
    type                           = "github"
    repository                     = "hugoreleaser"
    repository_owner               = "bep"
    generate_release_notes_on_host = true
    draft                          = true
    prerelease                     = true

[[builds]]
    path = "unix"

    [[builds.os]]
        goos = "darwin"
        [[builds.os.archs]]
            goarch = "universal"

    [[builds.os]]
        goos = "linux"
        [[builds.os.archs]]
            goarch = "amd64"

[[builds]]
    path = "windows"

    [[builds.os]]
        goos = "windows"
        [builds.os.build_settings]
            binary = "hugo.exe"
        [[builds.os.archs]]
            goarch = "amd64"

[[archives]]
    paths = "/builds/unix/**"
[[archives]]
    paths = "/builds/**/linux/amd64"
    [archives.archive_settings]
        [archives.archive_settings.type]
            format    = "_plugin"
            extension = ".deb"
        [archives.archive_settings.plugin]
            id      = "deb"
            type    = "gorun"
            command = "github.com/bep/hugoreleaser/plugins/archiveplugins/deb@latest"
        [archives.archive_settings.custom_settings]
            vendor      = "bep"
            homepage    = "https://github.com/bep/hugoreleaser"
            maintainer  = "Bjørn Erik Pedersen <bjorn.erik.pedersen@gmail.com>"
            description = "Build, archive and release Go programs."
            license     = "Apache-2.0"
[[archives]]
    paths = "/builds/windows/**"
    [archives.archive_settings]
        [archives.archive_settings.type]
            format    = "zip"
            extension = ".zip"

[[releases]]
    paths = "/archives/**"
    path  = "myrelease"
